### ISSUE TITLE
Props are updated (on store) but component is not re-rendering 

### ISSUE THREAD

**Issue by sidati** [developit/unistore#80]
Hi @developit ,
Hope you are doing well, im pulling my hair to figure out why this is happening with no luck, can you please take a look at this repo : 
https://github.com/sidati/unistore-test

thanks in advance ;)

**Comment by sidati** [comment]
Video : https://twitter.com/twitter/statuses/972442750611312640

**Comment by tzkmx** [comment]
Kinda difficult to give it a look through the webpack bundling, would you mind to share a more readable source?

**Comment by BDQ** [comment]
@sidati - I've seen this before - I think it's because your action is mutating the incoming state object.  It should return a NEW state object, if you change your `actions` to something like:

````javascript
let actions = store => ({
	addItem(state, id, data) {
		return {
			...state,
			order: {
				...state.order,
				items: [...state.order.items, data]
			}
		}
	}
})
````

And then it should start re-rendering as you expect.


@developit & all - should we warn when the state is being mutated to save this kind of confusion (which tripped me up for a while too).

**Comment by sidati** [comment]
Hi @tzkmx, Sorry for the delay but i believe all in this file :
https://github.com/sidati/unistore-test/blob/master/test.jsx

Hi @BDQ, I'll test it and get back to you

**Comment by tzkmx** [comment]
Thanks for sharing your test. I agree with @BDQ the issue is that your addItem function would mutate the store object. Besides, if you look at the implementation of [the method that binds your action creator to the store](https://github.com/developit/unistore/blob/ac6dc1a90ef65835935846235db7477dc993154a/src/index.js#L48-L63), the result of your function is merged into the store, and what i can look at, it's like you are adding the addItem method to the store, rather than applying the function and then returning the data to be merged.

Maybe something like this:

```javascript
let boundAddItem = ({order}, id, data) => {
    const updatedOrder = order
    updatedOrder.items[id] = data
    return updatedOrder
}
```

**Comment by developit** [comment]
Sorry for the delay!  Unistore's `connect()` will only update your component with new selected state values if they are different from the last ones.  Because you're mutating the store in-place, the value is always just a reference to the same object:

```js
let actions = store => ({
	addItem(state, id, data) {
		// current in-place mutation:  `state.order` is always the same object
		state.order.items[id] = data;
		return state;
	}
})
```

I'd recommend doing something like this:

```js
let actions = store => ({
	addItem({ order }, id, data) {
		// make a copy of order
		order = {
			...order,
			// but replace order.items with a new copy
			items: {
				...order.items,
				// with our data set:
				[id]: data
			}
		};
		return state;
	}
})
```

FWIW I frequently recommend the `immutability-helper` library for this, though it's a bit heavy (1.5kb).  There's also [Immer](https://github.com/mweststrate/immer) (900b), or you could roll your own :)

**Comment by sidati** [comment]
@developit, Its exactly what a did eventually, i was misguided by the demo :(
